name: LandLord
main: net.ddns.vcccd.Main
version: 1.0
api-version: '1.20'
commands:
  property:
    description: Gives you the property wand
    usage: /<command>
    permission: landlord.getwand
  removerenter:
    description: Gives you the renter remover
    usage: /<command>
    permission: landlord.getremover
  managehouses:
    description: Pulls up the deed menu to manage your houses
    usage: /<command>
    permission: landlord.getremover
