# In-game cost to register a Home
HomeRegistrationFee: 100.00

# Amount of days that will pass by before rent is collected
DaysBeforeRent: 1

# Amount of money you will collect on rent
RentMoney: 100.00

# The amount you get back when you sell a home (Should be less than registration fee)
SellAmount: 50.00

# The maximum cubic area of an acceptable property selection
MaxPropertySize: 5000